### ISSUE TITLE
question about clas slides 1 on page 19

### ISSUE THREAD

**Issue by philohistoria** [HKUST-SOSC4300-5500/Lecture-Material#1]
what is it?

**Comment by philohistoria** [comment]
@philohistoria @pengww-econ

**Comment by PercyPei** [comment]
Seems there's some problem when downloading the lecture materials. 
<img width="1255" alt="Screenshot 2020-09-08 at 11 06 32" src="https://user-images.githubusercontent.com/40018476/92429181-c12ba080-f1c3-11ea-82e3-333138992746.png">

**Comment by Garygcy1016** [comment]
> Seems there's some problem when downloading the lecture materials.
> <img alt="Screenshot 2020-09-08 at 11 06 32" width="1255" src="https://user-images.githubusercontent.com/40018476/92429181-c12ba080-f1c3-11ea-82e3-333138992746.png">

Hi Percy, I did not encounter this issue like you

**Comment by PercyPei** [comment]
Thanks! I'll try to check my browser settings.

**Comment by PercyPei** [comment]
Works fine on Chrome. Guess it's a browser issue.

**Comment by Garygcy1016** [comment]
> Works fine on Chrome. Guess it's a browser issue.

Oh yes, i am using Chrome too.

**Comment by philohistoria** [comment]
> Seems there's some problem when downloading the lecture materials.
> <img alt="Screenshot 2020-09-08 at 11 06 32" width="1255" src="https://user-images.githubusercontent.com/40018476/92429181-c12ba080-f1c3-11ea-82e3-333138992746.png">

You may download it directly if you cannot see it in your browser.
