### ISSUE TITLE
Question about Reading materials for class

### ISSUE THREAD

**Issue by ToniLaw** [HKUST-SOSC4300-5500/Lecture-Material#4]
Professor  @Zhang,

Besides the Bit By Bit textbook, where can I download the other readings for class?

Thank you!

-Toni

**Comment by philohistoria** [comment]
@ToniLaw If you have trouble accessing, I will put them on Canvas

**Comment by ToniLaw** [comment]
Ok, I don't know if it is just me but I could not seem to find the readings anywhere on Github. All I can download is the Lecture slides and the syllabus. If Professor Zhang you can upload the readings on Canvas or direct me to the material it would be great! 
Thank you.

**Comment by philohistoria** [comment]
@ToniLaw I cannot put all readings on GitHub. There are copyright concerns. I will upload them to Canvas and let you know!

**Comment by ToniLaw** [comment]
@philohistoria Understood, thank you for your help Professsor Zhang.

**Comment by ToniLaw** [comment]
@philohistoria Actually I was able to find most of readings via our HKUST library.

**Comment by philohistoria** [comment]
@ToniLaw Yes I think it should be the case. Nice to know! @pengww-econ
